version: '3.8'
services:
  auction_market:
    build:
      context: ./auction_market
    container_name: auction_market
    environment:
      - MARKET_DB_URI=mysql+pymysql://root:root@mysql:3306/market_db
    networks:
      - backend
    depends_on:
      - db-manager
      - mysql
  
  trading_history:
    build:
      context: ./trading_history
    container_name: trading_history
    environment:
      - MARKET_DB_URI=mysql+pymysql://root:root@mysql:3306/market_db
    networks:
      - backend
    depends_on:
      - db-manager
      - mysql
  
  db-manager:
    build:
      context: ./dbm
    container_name: db_manager
    ports:
      - "5001:5000" # Esposta per debug
    networks:
      - backend
    depends_on:
      - mysql
    environment:
      - MARKET_DB_URI=mysql+pymysql://root:root@mysql:3306/market_db
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8080:80" #accesso user
      - "8081:81" #accesso admin
    networks:
      - frontend
      - backend
      - admin_frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auction_market
      - trading_history
    restart: on-failure

networks:
  frontend:
  backend:
  admin_frontend:
