
name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usa una versione recente di Node.js

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Newman with the Postman collection
      - name: Run Postman tests
        run: |
          newman run /docs/postman-tests/Market_Tests.postman_collection.json \
            --reporters cli,junit \
            --reporter-junit-export test-results.xml

      # Step 5: Upload test results (opzionale, per visibilità)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-results
          path: test-results.xml
